# Zeabur 部署配置 - 街巷社区互助平台（前后端分离）

# 构建配置 - 前端
build:
  # 使用专门的 Dockerfile
  dockerfile: Dockerfile
  context: .

# 环境变量配置
env:
  # 后端 API 地址（在 Zeabur 中，后端服务可以通过内部网络访问）
  NEXT_PUBLIC_API_URL: "http://backend:8080"

  # JWT认证配置
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

  # Next.js 配置
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

  # 应用配置
  NODE_ENV: production

# 资源分配
resources:
  cpu: 0.5
  memory: 512Mi

# 健康检查
healthCheck:
  path: /
  port: 8080
  initialDelay: 30
  period: 10

# 端口配置
ports:
  - port: 8080
    protocol: HTTP

# 后端服务配置（作为独立服务部署）
services:
  backend:
    # 后端服务构建配置 - 使用专门的 Dockerfile
    build:
      dockerfile: backend/Dockerfile
      context: .

    # 后端环境变量
    env:
      # 数据库配置（使用 SQLite 持久化存储）
      DATABASE_URL: "file:./data/data.db"
      # JWT认证配置
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      # 应用配置
      NODE_ENV: production
      # CORS 配置 - 允许前端访问
      FRONTEND_URL: "http://frontend:8080"

    # 后端资源分配
    resources:
      cpu: 0.5
      memory: 512Mi

    # 后端健康检查
    healthCheck:
      path: /health
      port: 8080
      initialDelay: 30
      period: 10

    # 后端端口配置
    ports:
      - port: 8080
        protocol: HTTP